apply plugin: 'com.android.library'

android {
    namespace "co.in.shopykart.plugins"
    compileSdk 34
    defaultConfig {
        minSdk 22
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':capacitor-android')
}
